### ISSUE TITLE
The purpose of the Location helper class

### ISSUE THREAD

**Issue by Yonava** [Joshua-Burdick/travelapp#26]
What are you using/ planning on using the Location class for under the classes directory?

**Comment by Joshua-Burdick** [comment]
Location.js was originally being used as a wrapper class for extracting information from the google maps API place object. It's functionality was limited purely to simplicity and readability.

It will likely be deleted soon unless a more determined purpose for it is found.

**Comment by Yonava** [comment]
I suggest deleting it now 🙃

**Comment by Joshua-Burdick** [comment]
It has been deleted
